### ISSUE TITLE
mqtt broker

### ISSUE THREAD

**Issue by remko2000** [sahilchaddha/homebridge-dafang#55]
I followed al the steps in the wiki (I installed mongodb on my hostraspberry 3(10.0.1.22) and it's running) and updated my json in homebridge but get an error:
`Error: listen EADDRINUSE: address already in use :::1883
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at /usr/lib/node_modules/homebridge-dafang/node_modules/mosca/lib/server.js:225:16
    at makeCall (/usr/lib/nod`

My homebridge is down because of this error.

With 'sudo lsof -i :1883' I get:
> COMMAND     PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
mosquitto 10783 mosquitto    5u  IPv4  45600      0t0  TCP *:1883 (LISTEN)
mosquitto 10783 mosquitto    6u  IPv6  45601      0t0  TCP *:1883 (LISTEN)
mosquitto 10783 mosquitto    9u  IPv4  43888      0t0  TCP 10.0.1.22:1883->10.0.1.67:65361 (ESTABLISHED)

10.0.1.22 is my hostraspberry 3 and it looks like there is also a tasmotaswitch(10.0.1.67) with some kind of mosquitobroker linked to my raspberry. How do I solve this error?

**Comment by mkormendy** [comment]
@remko2000 it appears that you need to do more research on MQTT, there are plenty of guides out there.
